(function(){
 const Q=s=>document.querySelector(s), Sel=window.PIMSelectors;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const badge=(t,c='')=>`<span class="badge ${c}">${esc(t||'TBC')}</span>`;
 function source(record){const s=Sel.sourceFor(record);if(!s)return '';return `<button class="source-link" data-source='${esc(JSON.stringify(s))}'>Sumber: ${esc(s.judulFile||s.jenisSumber)} ⓘ</button>`;}
 function metric(label,value,sub='',record=null){return `<article class="metric"><small>${esc(label)}</small><strong>${esc(value)}</strong><span>${esc(sub)}</span>${record?source(record):''}</article>`;}
 function renderDashboard(){const d=Sel.dashboard();Q('#dashboard').innerHTML=`<div class="metrics">${metric('VIP roster',d.vip,'TAMU',Sel.headcount('HC-003'))}${metric('Raker RKAP',d.raker,'resmi',Sel.headcount('HC-001'))}${metric('Plenary',d.plenary,'orang',Sel.headcount('HC-002'))}${metric('Kendaraan',d.vehicles,`${d.minPI} PI · ${d.addPIM} PIM`,Sel.data('KENDARAAN')[0])}${metric('Rumah Komplek',`${d.occupied}/${d.capacity}`,`${d.capacity-d.occupied} tersedia · ${d.tbc} TBC`,Sel.data('AKOMODASI')[0])}${metric('Validasi',`${d.validation.errors} error`,`${d.validation.warnings} warning`)}</div><section class="panel"><h2>Readiness per acara</h2>${Sel.readiness().map(r=>`<div class="progress-row"><div><b>${esc(r.event)}</b><small>${r.total} checklist · ${r.blocked} blocked</small></div><progress max="100" value="${r.progress}"></progress><b>${r.progress}%</b></div>`).join('')}</section><section class="panel"><h2>Perlu perhatian</h2><p>${d.issues.length} issue aktif · ${d.impacts.length} impact review terbuka.</p></section>`;}
 function renderChecklist(){const rows=Sel.data('CHECKLIST').filter(Sel.active);Q('#checklist').innerHTML=table(['Item','Acara','Owner','PIC','Deadline','Status','Progress'],rows.map(r=>[r.itemChecklist,Sel.name('ACARA',r.idAcara,'namaSingkat'),Sel.name('ORGANISASI',r.idOwner,'namaSingkat'),Sel.name('PERSONEL',r.idPic,'nama'),r.deadline||'Belum ditetapkan',badge(r.status),`${r.progress||0}%`]),rows);}
 function renderIssues(){const rows=Sel.data('ISSUES').filter(Sel.active);Q('#issues').innerHTML=table(['Issue','Acara','PIC','Prioritas','Status','Deadline'],rows.map(r=>[r.issue,Sel.name('ACARA',r.idAcara,'namaSingkat'),Sel.name('PERSONEL',r.idPic,'nama'),badge(r.prioritas,String(r.prioritas||'').toLowerCase()),badge(r.status),r.deadline||'Belum ditetapkan']),rows);}
 function renderRundown(){const rows=Sel.data('RUNDOWN').filter(Sel.active).sort((a,b)=>String(a.mulaiDatetime).localeCompare(String(b.mulaiDatetime))||(a.urutanTampilan||0)-(b.urutanTampilan||0));Q('#rundown').innerHTML=rows.map(r=>`<article class="timeline-card"><time>${esc(Sel.fmtDateTime(r.mulaiDatetime))}–${esc(r.selesai||'')}</time><div><h3>${esc(r.kegiatan)}</h3><p>${esc(r.jalur)} · ${esc(Sel.name('VENUE',r.idVenueTujuan||r.idVenueAsal,'namaSingkat'))}</p>${source(r)}</div></article>`).join('')||empty();}
 function renderGuests(){const rows=Sel.guests();Q('#tamu').innerHTML=`<div class="card-grid">${rows.map(g=>`<article class="card"><div class="card-head"><div><h3>${esc(g.namaLengkap)}</h3><p>${esc(g.jabatan)} · ${esc(g.organisasi)}</p></div>${badge(g.kategori)}</div><dl><dt>Datang</dt><dd>${esc(Sel.travelLabel(g,'Datang'))}</dd><dt>Pulang</dt><dd>${esc(Sel.travelLabel(g,'Pulang'))}</dd><dt>LO</dt><dd>${esc(g.lo.map(x=>{const lo=Sel.by('LO',x.idLo);return lo?Sel.name('PERSONEL',lo.idPersonel,'nama'):'Belum ditentukan';}).join(', ')||'Belum ditentukan')}</dd><dt>Akomodasi</dt><dd>${esc(g.accommodation.map(x=>x.unit?.namaUnit||x.status).join(', ')||'Belum tersedia')}</dd></dl>${source(g)}</article>`).join('')}</div>`;}
 function renderLO(){const los=Sel.data('LO').filter(Sel.active),assign=Sel.data('PENUGASAN_LO').filter(Sel.active);Q('#lo').innerHTML=`<div class="card-grid">${los.map(l=>{const handled=assign.filter(a=>a.idLo===l.idLo).map(a=>Sel.name('TAMU',a.idTamu,'namaLengkap')).filter(x=>x!=='Data terkait belum tersedia');return `<article class="card"><h3>${esc(Sel.name('PERSONEL',l.idPersonel,'nama'))}</h3><p>${esc(l.peran)} · ${esc(Sel.name('PERSONEL',l.idPersonel,'jabatanUtama'))}</p><b>Menangani</b><p>${esc(handled.join(', ')||'Belum ditentukan')}</p></article>`;}).join('')}</div>`;}
 function renderAccommodation(){const units=Sel.data('AKOMODASI').filter(Sel.active),assign=Sel.data('PENUGASAN_AKOMODASI').filter(Sel.active),home=units.filter(x=>x.tipe==='Rumah Komplek');Q('#akomodasi').innerHTML=`<div class="metrics">${metric('Kapasitas Rumah',home.reduce((s,x)=>s+Number(x.kapasitas||0),0),'slot')}${metric('Teridentifikasi',assign.filter(x=>x.status==='Confirmed'&&x.idAkomodasi).length,'assignment ber-ID')}${metric('TBC',Sel.headcount('HC-012')?.nilaiEfektif||15,'tamu')}</div><div class="card-grid">${home.map(u=>{const occupants=assign.filter(a=>a.idAkomodasi===u.idAkomodasi&&a.status==='Confirmed');return `<article class="card"><h3>${esc(u.namaUnit)}</h3><p>Kamar ${esc(u.nomorKamar)} · ${badge(u.kesiapan)}</p><p>${occupants.map(a=>esc(Sel.name('TAMU',a.idTamu,'namaLengkap'))).join(', ')||'Tersedia'}</p></article>`;}).join('')}</div>`;}
 function renderVehicles(){const rows=Sel.data('KENDARAAN').filter(Sel.active);Q('#kendaraan').innerHTML=table(['ID','Tipe','Kapasitas','Sumber','Provider','Status'],rows.map(r=>[r.idKendaraan,r.tipe,r.kapasitasPenumpang,r.sumberPenyediaan,Sel.name('ORGANISASI',r.idProvider,'namaSingkat'),badge(r.status)]),rows);}
 function renderConsumption(){const rows=Sel.data('KONSUMSI').filter(Sel.active);Q('#konsumsi').innerHTML=table(['Kegiatan','Jenis','Dasar','Buffer','Final','Waktu','Venue','Status'],rows.map(r=>[r.kegiatanRujukan,r.jenisKonsumsi,r.jumlahDasar,`${Math.round(Number(r.buffer||0)*100)}%`,r.jumlahFinal,Sel.fmtDateTime(r.waktuKonsumsi),Sel.name('VENUE',r.idVenue,'namaSingkat'),badge(r.status)]),rows);}
 function table(headers,rows,records){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}<th>Sumber</th></tr></thead><tbody>${rows.map((r,i)=>`<tr>${r.map(v=>`<td>${typeof v==='string'&&v.startsWith('<span')?v:esc(v)}</td>`).join('')}<td>${source(records[i])}</td></tr>`).join('')}</tbody></table></div>`;}
 function empty(){return '<div class="empty">Data terkait belum tersedia.</div>';}
 function bindSources(){document.body.addEventListener('click',e=>{const b=e.target.closest('[data-source]');if(!b)return;try{const s=JSON.parse(b.dataset.source);Q('#source-title').textContent=s.judulFile||s.jenisSumber;Q('#source-body').innerHTML=`<p><b>Jenis:</b> ${esc(s.jenisSumber||'—')}</p><p><b>Versi:</b> ${esc(s.versiTanggal||'—')}</p><p><b>Status:</b> ${esc(s.status||'—')}</p><p><b>Metode:</b> ${esc(s.method||'—')}</p><p><b>Filter/eksklusi:</b> ${esc(s.filters||'—')}</p><p><b>Perbandingan:</b> ${esc(s.comparison||'—')}</p><p><b>Referensi:</b> ${esc(s.referensi||'—')}</p><p><b>Data dibuat:</b> ${esc(window.PIMStore.state.payload?.generatedAt||'—')}</p>`;Q('#source-dialog').showModal();}catch(_){}});}
 function renderAll(){renderDashboard();renderChecklist();renderIssues();renderRundown();renderGuests();renderLO();renderAccommodation();renderVehicles();renderConsumption();bindSources();}
 window.PIMRenderers={renderAll};
})();
